[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  GIT_LFS_ENABLED = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
